spring.application.name=land-registry-backend
spring.datasource.url=jdbc:mysql://localhost:3306/land_registry
spring.datasource.username=root
spring.datasource.password=Mishraji04$()

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect